apiVersion: neuvector.com/v1
kind: NvWafSecurityRule
metadata:
  name: sql-injection
  namespace: juice-shop
spec:
  sensor:
    name: sql-injection
    comment: "OWASP Top 10 Injection Mitigation custom regex sensor"
    rules:
      - name: auth-bypass
        patterns:
          - key: pattern
            op: regex
            value: |
              '(?:\s|[^a-zA-Z0-9_])OR(?:\s+|\()1=1(?:-|\s*\)|[^a-zA-Z0-9_])
            context: packet
---
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  # THE FIX: A safe K8s name that NeuVector will NOT delete. Fleet tracks this perfectly.
  name: juice-shop-waf-policy 
  namespace: juice-shop
spec:
  target:
    policymode: Protect
    selector:
      # THE TARGET: Modifying NeuVector's system group directly
      name: nv.juice-shop.juice-shop
      criteria:
        - key: domain
          op: "="
          value: juice-shop
        - key: service
          op: "="
          value: juice-shop.juice-shop
  waf:
    status: true
    settings:
      - name: sql-injection
        action: deny
  
  # Decouples process crashes: Node.js boots normally
  process_profile:
    baseline: basic
    mode: Discover

  # Authorizes the Ingress controller to talk to the app
  ingress:
    - action: allow
      ports: any
      applications:
        - HTTP
      name: gitops-allow-ingress-controller
      selector:
        name: ingress
  egress: []
  process: []
  file: []
